name: restaurant-api
on:
  push:
    branches: [main]
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v4.0.1
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: donet build --no-restore
        - name: Test
          run: donet test
